{{- if .Values.appConfig.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cpemon.configMapName" . | quote }}
  namespace: {{ include "cpemon.namespace" . | quote }}
  labels:
{{ include "cpemon.labels" . | nindent 4 }}
data:
  HTTP_ADDR: {{ .Values.appConfig.httpAddr | quote }}
  GRAFANA_HOME_URL: {{ .Values.appConfig.grafanaHomeUrl | quote }}
  GRAFANA_SN_DASHBOARD_URL_TEMPLATE: {{ .Values.appConfig.grafanaSnDashboardUrlTemplate | quote }}
  KIBANA_HOME_URL: {{ .Values.appConfig.kibanaHomeUrl | quote }}
  KIBANA_SN_LOGS_URL_TEMPLATE: {{ .Values.appConfig.kibanaSnLogsUrlTemplate | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.appConfig.kafkaBootstrapServers | quote }}
  KAFKA_TOPIC_DEVICE_HEARTBEAT: {{ .Values.appConfig.kafkaTopicDeviceHeartbeat | quote }}
  KAFKA_TOPIC_WAN_STATUS: {{ .Values.appConfig.kafkaTopicWanStatus | quote }}
  KAFKA_TOPIC_DEADLETTER: {{ .Values.appConfig.kafkaTopicDeadletter | quote }}
  KAFKA_PRODUCER_ENABLED: {{ .Values.appConfig.kafkaProducerEnabled | quote }}
  KAFKA_PRODUCER_TIMEOUT: {{ .Values.appConfig.kafkaProducerTimeout | quote }}
  KAFKA_PRODUCER_MAX_RETRIES: {{ .Values.appConfig.kafkaProducerMaxRetries | quote }}
{{- end }}
