{{- if .Values.pdb.enabled }}
{{- $root := . -}}
{{- range $name, $workload := .Values.workloads }}
{{- $pdbWorkload := index $root.Values.pdb.workloads $name }}
{{- if and $workload.enabled $pdbWorkload.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ printf "%s-pdb" $workload.name | quote }}
  namespace: {{ include "cpemon.namespace" $root | quote }}
  labels:
{{ include "cpemon.workloadLabels" (dict "root" $root "workload" $workload) | nindent 4 }}
spec:
  minAvailable: {{ $root.Values.pdb.minAvailable }}
  selector:
    matchLabels:
{{ include "cpemon.selectorLabels" (dict "root" $root "workload" $workload) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
