{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.store.create }}
{{- $eso := .Values.externalSecrets -}}
apiVersion: {{ $eso.apiVersion | quote }}
kind: {{ $eso.store.kind | quote }}
metadata:
  name: {{ $eso.store.name | quote }}
  namespace: {{ include "cpemon.namespace" . | quote }}
  labels:
    {{- include "cpemon.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: {{ $eso.store.provider.aws.service | quote }}
      region: {{ $eso.store.provider.aws.region | quote }}
      {{- with $eso.store.provider.aws.roleArn }}
      role: {{ . | quote }}
      {{- end }}
{{- end }}
