apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cpemon
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: cpemon
    cpemon.io/layer: delivery
    cpemon.io/managed-by: argocd
spec:
  description: CPEmon learning GitOps project for application and platform add-on deployment.
  sourceRepos:
    - https://github.com/huangruidtu/cpemon-mvp.git
    - registry-1.docker.io/bitnamicharts
    - ghcr.io/prometheus-community/charts
    - https://charts.external-secrets.io
    - https://argoproj.github.io/argo-helm
  destinations:
    - namespace: cpemon
      server: https://kubernetes.default.svc
    - namespace: kafka
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: security
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: argo-rollouts
      server: https://kubernetes.default.svc
    - namespace: platform
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: apiregistration.k8s.io
      kind: APIService
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
