apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-aws
  labels:
    app.kubernetes.io/name: provider-family-aws
    app.kubernetes.io/part-of: cpemon-mvp
    cpemon.io/layer: platform-control-plane
    cpemon.io/managed-by: argocd
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v2.0.0
  runtimeConfigRef:
    name: aws-irsa-runtime
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-irsa-runtime
  labels:
    app.kubernetes.io/name: provider-family-aws
    app.kubernetes.io/part-of: cpemon-mvp
    cpemon.io/layer: platform-control-plane
    cpemon.io/managed-by: argocd
spec:
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/cpemon-crossplane-provider-aws-dev
      labels:
        app.kubernetes.io/part-of: cpemon-mvp
        cpemon.io/environment: dev
        cpemon.io/layer: platform-control-plane
