# syntax=docker/dockerfile:1

FROM golang:1.23-alpine AS builder
RUN apk add --no-cache git
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /bin/cpemon-writer ./app/cpemon-writer

FROM alpine:3.20
RUN adduser -D -u 10001 cpemon
WORKDIR /app
COPY --from=builder /bin/cpemon-writer /app/cpemon-writer
EXPOSE 8080
USER cpemon
ENTRYPOINT ["/app/cpemon-writer"]
