apiVersion: v1
kind: Secret
metadata:
  name: cpemon-db
  namespace: cpemon
  labels:
    app.kubernetes.io/name: cpemon-db
    app.kubernetes.io/part-of: cpemon-mvp
type: Opaque
stringData:
  dsn: ${CPEMON_DB_DSN}
---
apiVersion: v1
kind: Secret
metadata:
  name: cpemon-acs-hmac
  namespace: cpemon
  labels:
    app.kubernetes.io/name: cpemon-acs-hmac
    app.kubernetes.io/part-of: cpemon-mvp
type: Opaque
stringData:
  hmac-secret: ${CPEMON_ACS_HMAC_SECRET}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
  namespace: cpemon
  labels:
    app.kubernetes.io/name: mysql-auth
    app.kubernetes.io/part-of: cpemon-mvp
type: Opaque
stringData:
  mysql-root-password: ${MYSQL_ROOT_PASSWORD}
  mysql-username: ${MYSQL_USERNAME}
  mysql-password: ${MYSQL_PASSWORD}
  mysql-database: ${MYSQL_DATABASE}
