apiVersion: v1
kind: ConfigMap
metadata:
  name: cpemon-app-config
  namespace: cpemon
  labels:
    app.kubernetes.io/name: cpemon-app-config
    app.kubernetes.io/part-of: cpemon-mvp
data:
  HTTP_ADDR: ":8080"
  GRAFANA_HOME_URL: "https://grafana.local/"
  GRAFANA_SN_DASHBOARD_URL_TEMPLATE: "https://grafana.local/d/cpemon_cpe_detail?var_sn=%s"
  KIBANA_HOME_URL: "http://kibana.local/app/discover#/?_g=(time:(from:now-120m,to:now))&_a=(query:(language:kuery,query:''))"
  KIBANA_SN_LOGS_URL_TEMPLATE: "http://kibana.local/app/discover#/?_g=(time:(from:now-120m,to:now))&_a=(query:(language:kuery,query:'message:\"sn=%s\"'))"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_TOPIC_DEVICE_HEARTBEAT: "cpemon.device.heartbeat.v1"
  KAFKA_TOPIC_WAN_STATUS: "cpemon.wan.status.v1"
  KAFKA_TOPIC_DEADLETTER: "cpemon.deadletter.v1"
  WORKER_INTERVAL: "1s"
  BATCH_SIZE: "50"
