apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-dev
  namespace: argocd
  annotations:
    cpemon.io/sync-policy: manual
    cpemon.io/sync-prune: "disabled"
    cpemon.io/sync-self-heal: "disabled"
  labels:
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: cpemon-mvp
    cpemon.io/environment: dev
    cpemon.io/layer: progressive-delivery
    cpemon.io/managed-by: argocd
spec:
  project: cpemon
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-rollouts
      targetRevision: 2.41.0
      helm:
        releaseName: argo-rollouts
        valueFiles:
          - $values/k8s/addons/argo-rollouts/values.yaml
    - repoURL: https://github.com/huangruidtu/cpemon-mvp.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
