apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgpt-dev
  namespace: argocd
  annotations:
    cpemon.io/sync-policy: manual
    cpemon.io/sync-prune: "disabled"
    cpemon.io/sync-self-heal: "disabled"
  labels:
    app.kubernetes.io/name: k8sgpt
    app.kubernetes.io/part-of: cpemon-mvp
    cpemon.io/environment: dev
    cpemon.io/layer: detective-observability
    cpemon.io/managed-by: argocd
spec:
  project: cpemon
  sources:
    - repoURL: https://charts.k8sgpt.ai/
      chart: k8sgpt-operator
      targetRevision: 0.2.27
      helm:
        releaseName: k8sgpt
        valueFiles:
          - $values/k8s/addons/k8sgpt/values.yaml
    - repoURL: https://github.com/huangruidtu/cpemon-mvp.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgpt-operator-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
