apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-dev
  namespace: argocd
  annotations:
    cpemon.io/sync-policy: manual
    cpemon.io/sync-prune: "disabled"
    cpemon.io/sync-self-heal: "disabled"
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: cpemon-mvp
    cpemon.io/environment: dev
    cpemon.io/layer: governance
    cpemon.io/managed-by: argocd
spec:
  project: cpemon
  sources:
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.8.1
      helm:
        releaseName: kyverno
        valueFiles:
          - $values/k8s/addons/kyverno/values.yaml
    - repoURL: https://github.com/huangruidtu/cpemon-mvp.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
