apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-dev
  namespace: argocd
  annotations:
    cpemon.io/sync-policy: manual
    cpemon.io/sync-prune: "disabled"
    cpemon.io/sync-self-heal: "disabled"
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/part-of: cpemon-mvp
    cpemon.io/environment: dev
    cpemon.io/layer: monitoring
    cpemon.io/managed-by: argocd
spec:
  project: cpemon
  sources:
    - repoURL: ghcr.io/prometheus-community/charts
      chart: kube-prometheus-stack
      targetRevision: 86.3.2
      helm:
        releaseName: kps
        valueFiles:
          - $values/k8s/monitoring/kube-prometheus-stack-values.yaml
    - repoURL: https://github.com/huangruidtu/cpemon-mvp.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
