apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost-dev
  namespace: argocd
  annotations:
    cpemon.io/sync-policy: manual
    cpemon.io/sync-prune: "disabled"
    cpemon.io/sync-self-heal: "disabled"
  labels:
    app.kubernetes.io/name: opencost
    app.kubernetes.io/part-of: cpemon-mvp
    cpemon.io/environment: dev
    cpemon.io/layer: cost
    cpemon.io/managed-by: argocd
spec:
  project: cpemon
  sources:
    - repoURL: https://opencost.github.io/opencost-helm-chart
      chart: opencost
      targetRevision: 2.5.23
      helm:
        releaseName: opencost
        valueFiles:
          - $values/k8s/addons/opencost/values.yaml
    - repoURL: https://github.com/huangruidtu/cpemon-mvp.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
