apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: echo
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/component: platform-smoke-test
    cpemon.io/layer: platform-test
    cpemon.io/managed-by: gitops-ready-manifest
  name: echo
  namespace: platform
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
        app.kubernetes.io/part-of: cpemon-mvp
        app.kubernetes.io/component: platform-smoke-test
        cpemon.io/layer: platform-test
    spec:
      containers:
        - args:
            - -listen=:8080
            - -text=cpemon platform echo ok
          image: hashicorp/http-echo:1.0
          imagePullPolicy: IfNotPresent
          name: echo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
