apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
  labels:
    app.kubernetes.io/part-of: cpemon
    cpemon.io/story: CCPU-214
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.8.2
