apiVersion: v1
kind: Namespace
metadata:
  name: cpemon
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: cpemon
    cpemon.io/layer: application
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: platform
    cpemon.io/layer: platform
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: monitoring
    cpemon.io/layer: observability
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: argocd
    cpemon.io/layer: delivery
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: kafka
    cpemon.io/layer: data-streaming
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: security
    cpemon.io/layer: security
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: cost
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: cost
    cpemon.io/layer: finops
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: backup
    cpemon.io/layer: operations
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: argo-rollouts
    cpemon.io/layer: progressive-delivery
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: crossplane-system
    cpemon.io/layer: platform-control-plane
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8sgpt-operator-system
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: k8sgpt-operator-system
    cpemon.io/layer: detective-observability
    cpemon.io/managed-by: gitops-ready-manifest
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: ingress-nginx
    cpemon.io/layer: legacy-lab-ingress
    cpemon.io/managed-by: gitops-ready-manifest
